# This workflow will run integration tests on the java backend
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java integration tests

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./examples/integration-tests

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: debug step
      run: ls -lhAtr ; pwd
    - name: Grant execute permission for gradlew
      run: chmod +x ../java/merchant/gradlew
    - name: Grant execute permission for testscript
      run: chmod +x test-java.sh
    - name: Run Java integration test
      run: ./test-java.sh
        env:
          API_KEY: ${{ secrets.API_KEY }}
          MERCHANT_ID: ${{ secrets.MERCHANT_ID }}
          LARGE_SECRET_PASSPHRASE: ${{ secrets.MERCHANT_TOKEN }}
