# This workflow will run integration tests on the node backend

name: Node integration tests

# Run this workflow always 
on: workflow_dispatch
#  push:
#    branches: [ * ]
#  pull_request:
#    branches: [ * ]


jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./examples/node.js

    steps:
    - uses: actions/checkout@v2
    - name: Set up node
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
    - name: Install npm
      run: npm install
      working-directory: ./examples/node.js
    - name: Test npm
      run: npm test
      working-directory: ./examples/node.js
    
    - name: Run Node integration test
      shell: bash
      working-directory: ./examples/integration-tests
      env:
        API_KEY: ${{ secrets.API_KEY }}
        MERCHANT_ID: ${{ secrets.MERCHANT_ID }}
        LARGE_SECRET_PASSPHRASE: ${{ secrets.MERCHANT_TOKEN }}
      run: ./test-node.sh
