# This workflow will run integration tests on the node backend

name: Node integration tests

# Run this workflow always 
on: [push, pull_request, workflow_dispatch]
#on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./examples/node.js

    steps:
    - uses: actions/checkout@v2
    - name: Set up node
      uses: actions/setup-node@v3.0.0
      with:
        node-version: '16'
        cache: 'npm'
        cache-dependency-path: './examples/node.js/package-lock.json'
    - run: npm install

    - name: Copy config file
      shell: bash
      run: cp example.appconfig.json appconfig.json
    
    - name: Run Node integration test
      env:
        API_KEY: ${{ secrets.API_KEY }}
        MERCHANT_ID: ${{ secrets.MERCHANT_ID }}
        LARGE_SECRET_PASSPHRASE: ${{ secrets.MERCHANT_TOKEN }}
        MERCHANT_TOKEN: ${{ secrets.MERCHANT_TOKEN }}
        SWBPAY_merchantId: ${{ secrets.MERCHANT_ID }}
        SWBPAY_apiKey: ${{ secrets.API_KEY }}
        SWBPAY_merchantToken: ${{ secrets.MERCHANT_TOKEN }}
      run: npm test
