# This workflow will run integration tests on the node backend

name: Node integration tests

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./examples/node.js

    steps:
    - uses: actions/checkout@v2
    - name: Set up node
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
    - run: npm install
    - run: npm test
    
    - name: Run Node integration test
      shell: bash
      working-directory: ./examples/integration-tests
      env:
        API_KEY: ${{ secrets.API_KEY }}
        MERCHANT_ID: ${{ secrets.MERCHANT_ID }}
        LARGE_SECRET_PASSPHRASE: ${{ secrets.MERCHANT_TOKEN }}
      run: ./test-node.sh
