# This workflow will run integration tests on the java backend
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Node integration tests

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./examples/integration-tests

      steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: NodeJob
      with:
        node-version: '16'
        cache: 'npm'
      - run: npm install
      - run: npm test
      - name: debug step
        run: ls -lhAtr ; pwd
      - name: Run Node integration test
        shell: bash
        env:
          API_KEY: ${{ secrets.API_KEY }}
          MERCHANT_ID: ${{ secrets.MERCHANT_ID }}
          LARGE_SECRET_PASSPHRASE: ${{ secrets.MERCHANT_TOKEN }}            run: ./test-node.sh
